name: CI debug

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx1024m

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: ENV variables
        env:
          APP_SIGN_ALIAS: ${{ secrets.APP_SIGN_ALIAS }}
          APP_SIGN_PASSWORD: ${{ secrets.APP_SIGN_PASSWORD }}
          APIKEY_NEWS: ${{ secrets.APIKEY_NEWS }}
          APIKEY_WEATHER: ${{ secrets.APIKEY_WEATHER }}
        run: |
          touch ./local.properties \
          echo signing.alias=\"$APP_SIGN_ALIAS\" >> ./local.properties \
          echo signing.pas=\"$APP_SIGN_PASSWORD\" >> ./local.properties \
          echo apikey.news=\"$APIKEY_NEWS\" >> ./local.properties \
          echo apikey.weather=\"$APIKEY_WEATHER\" >> ./local.properties \
          cat ./local.properties
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Unit tests
        run: ./gradlew testDebugUnitTest --stacktrace
