name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: ENV variables
        env:
          APP_SIGN_ALIAS: ${{ secrets.APP_SIGN_ALIAS }}
          APP_SIGN_PASSWORD: ${{ secrets.APP_SIGN_PASSWORD }}
        run: |
          echo signing.alias=\"APP_SIGN_ALIAS\" > ./local.properties \
          echo signing.password=\"APP_SIGN_PASSWORD\" > ./local.properties \
      - name: Build with Gradle
        run: ./gradlew assembleDebug
