name: CI debug

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: ENV variables
        env:
          APP_SIGN_ALIAS: ${{ secrets.APP_SIGN_ALIAS }}
          APP_SIGN_PASSWORD: ${{ secrets.APP_SIGN_PASSWORD }}
          APIKEY_NEWS: ${{ secrets.APIKEY_NEWS }}
        run: |
          touch ./local.properties
          echo apikey.news=\"APIKEY_NEWS\" >> ./local.properties \
          echo signing.alias=\"APP_SIGN_ALIAS\" >> ./local.properties \
          echo signing.password=\"APP_SIGN_PASSWORD\" >> ./local.properties \
          cat ./local.properties
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Unit tests --stacktrace
        run: ./gradlew testDebugUnitTest
